""" 
'launch.py'
Launches Web Server and opens observation map 
'photo_map.html' generated by 'map.py'
author: Dr. Hakim Mitiche
update: Jan. 2026
"""

import subprocess
import webbrowser
import time
import sys, os


PORT = 8000
#HTML_FILE = "photo_map.html"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
HTML_FILE = os.path.join(BASE_DIR, "photo_map.html")



def start_server_and_open_map():

    print(f"Starting local HTTP server on port {PORT}...")

    # Start server in background
    server_process = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(PORT)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    # Wait for server to initialize
    time.sleep(2)

    url = f"http://localhost:{PORT}/{HTML_FILE}"

    print("Opening map:", url)
    webbrowser.open(url)

    return server_process


if __name__ == "__main__":

    if not os.path.isfile(HTML_FILE):
        print(f"[ERROR] Map file not found: {os.path.abspath(HTML_FILE)}")
        print("Make sure 'map.py' was run and created the HTML file.")
        sys.exit(1) 

    server_process = start_server_and_open_map()

    input("\nPress ENTER to stop the server...\n")

    server_process.terminate()
    print("Server stopped.")
